sudo: required
dist: trusty
language:
  - java
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
    packages:
      - bazel

script:
  # Check our installs.
  - bazel version
  # Check that all of our tools and samples build
  - bazel build --noshow_progress //...
  # Check that all of our tests pass
  - bazel test --noshow_progress //...
